#!/usr/bin/env sh
. "$(dirname -- "$0")/_/husky.sh"

# обычно тут запускать только линтеры, тошо все остальное долго

# npm run build:prod
npm run lint:ts
npm run lint:scss
# npm run test:unit
# npm run storybook:build
# npm run test:ui